config/routes.rb
Rails.application.routes.draw do

# resources :users do
#   resources :items
# end
#
#
# resources :users do
#   resources :orders
#   end



  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy'


  get "/users/:user_id/items" => "items#index", as: :user_items
  post "/users/:user_id/items" => "items#create"
  get "/users/:user_id/items/new" => "items#new", as: :new_user_item
  get "/users/:user_id/items/:id/edit" => "items#edit", as: :edit_user_item
  get "/users/:user_id/items/:id" => "items#show", as: :user_item
  patch "/users/:user_id/items/:id" => "items#update"
  delete "/users/:user_id/items/:id" => "items#destroy"
  get "/users" => "users#index", as: :user
  post "/users" => "users#create"
  get "/users/new" => "users#show", as: :new_user
  get "/users/:id/edit" => "users#edit", as: :edit_user
  get "/users/:id" => "users#show"
  patch "/users/:id" => "users#update"
  delete "/users/:id" => "users#destroy"
  get "/orders" => "orders#index", as: :orders
  post "/orders" => "orders#create"
  get "/orders/new" => "orders#new", as: :new_order
  get "/orders/:id" => "orders#edit", as: :edit_order
  get "/orders/:id" => "orders#show", as: :order
  patch "/orders/:id" => "orders#update"
  delete "/orders/:id" => "orders#destroy"
  get "/users" => "users#index"
  post "/users" => "users#create"
  get "/users/new" => "users#new"
  get "/users/:id/edit" => "users#edit"
  get "/users/:id" => "users#show", as: :particular_user
  patch "/users/:id" => "users#update"
  delete "/users/:id" => "users#destroy"







  #
  # get "users" => "users#index", as: :users
  # get "users/new" => "users#new", as: :new_user
  # get "users/:user_id" => "users#show", as: :user
  # post "users" => "users#create"
  # get "users/:current_user_id/edit" => "users#edit", as: :edit_user
  # patch "users/:current_user_id/" => "users#update"
  #
  #
  #
  # get "users/:user_id/items" => "items#index",   as: :user_items
  # get "users/:current_user_id/items/new" => "items#new", as: :new_user_item
  # get "users/:user_id/items/:item_id" => "items#show", as: :user_item
  # get "users/:current_user_id/items" => "items#current_user_items", as: :current_user_items
  # get "users/:current_user_id/items/:item_id" => "items#current_user_item", as: :current_user_item
  # post "users/:current_user_id/items" => "items#create"
  # get "users/:current_user_id/items/:item_id/edit" => "items#edit", as: :edit_user_item
  # patch "users/:current_user_id/items/:item_id" => "items#update"
  # delete "users/:current_user_id/items/:item_id" => "items#destroy"
  #
  # get "users/:current_user_id/orders/new" => "orders#new", as: :new_order
  # post "users/:current_user_id/orders/" => "orders#create"
  #
  # get "users/:user_id/items/:item_id/orders/:order_id/orderlines" => "orderlines#index", as: :order_orderlines
  # get "users/:user_id/items/:item_id/orders/:order_id/orderlines/new" => "orderlines#new", as: :new_order_orderlines

  # resources :users do
  #   resources :items
  # end
  #
  # resources :users do
  #   resources :orders
  # end


end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :orderlines
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :orderlines
end

app/models/orderline.rb
class Orderline < ActiveRecord::Base
  belongs_to :order
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :items
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
	end

  def current_order
    @current_order ||= Order.find_by(id: session[:order_id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def item_list
		@item = Item.all
	end

	def index
    @user = User.find(params[:user_id])
		@item = @user.items.all
	end

	def show
    @user = User.find(params[:user_id])
    @item = @user.items.find(params[:id])
	end

  def current_user_items
    @user = User.find(current_user.id)
    @item = @user.items.all
  end

  def current_user_item
    @user = User.find(current_user.id)
    @item = Item.find(params[:id])
    # @item.user_id = current_user.id
  end

	def new
		@user = User.find(current_user.id)
		@item = Item.new
	end

	def create
		 @user = User.find(current_user.id)
		 @item = Item.new(item_params)
		 @item.user_id = current_user.id

		 # @items = @user.items.create(item_params)

		if @item.save
		  redirect_to user_items_path
		else
		  render :new
		end
	end


	def edit
		@user = User.find(current_user.id)
		@item = Item.find(params[:id])
		# @item.user_id = current_user.id
	end

	def update
		@user = User.find(current_user.id)
		@item = Item.find(params[:id])
		# @item.user_id = current_user.id

		if @item.update_attributes(item_params)
			redirect_to user_item_path
		else
			render :edit
		end
	end

	def destroy
    @user = User.find(current_user.id)
		@item = Item.find(params[:id])
		@item.destroy
		redirect_to user_items_path
	end

private
	def item_params
	  params.require(:item).permit(:item_name, :user_id, :orderline_id, :stock_quantity, :marked_price, :created_at, :updated_at)
	end




end

app/controllers/orderlines_controller.rb
class OrderlinesController < ApplicationController
  def index
  end

  def show
  end

  def new
    @user = User.find(current_user.id)
    @order = User.order.find(:id)
		@orderline = Orderline.new
	end

  def create
    @user = User.find(current_user.id)
    @order = User.order.find(:id)
    @orderline = Orderline.new(orderline_params)

   if @orderline.save
     redirect_to user_path(current_user)
   else
     render :new
   end
 end

 private
 	def orderline_params
 	  params.require(:orderline).permit(:quantity, :order_id, :item_id, :total_price, :created_at, :updated_at)
 	end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @user = User.find(current_user.id)
    @orders = @user.orders.all
  end

  def show
    @user = User.find(current_user.id)
    @order = @user.orders.find(params[:id])
  end

  def new
    @user = User.find(current_user.id)
    @order = User.order.find(:id)
    @order = Order.new
		@orderline = Orderline.new
  end

  def create
    @user = User.find(current_user.id)
    @order = User.order.find(:id)
    @orderline = Orderline.new(orderline_params)

     if @orderline.save
       @order.user_id = current_user.id
       redirect_to user_path(current_user)
     else
       render :new
     end
  end

  private
  	def order_params
  	  params.require(:order).permit(:user_id, :created_at, :updated_at)
  	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
#comment
  def create
    user = User.find_by(email: params[:login][:email])

    if user && user.authenticate(params[:login][:password])
      session[:user_id] = user.id.to_s
      redirect_to users_path
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create

    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)

    if @user.update_attributes(user_params)
    redirect_to users_path
    else
    render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orderlines_helper.rb
module OrderlinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form_user_item.html.erb
<h1><%= @user.first_name %>'s <%= @item.item_name %></h1>

<table>
	<tr>
    <th> Item ID </th>
		<th> Item Name </th>
		<th> Stock Quantity </th>
		<th> Marked_Price </th>
		<th> Posted Time </th>
	</tr>
		<tr>
      <td> <%= @item.id %> </td>
			<td> <%= @item.item_name %> </td>
			<td> <%= @item.stock_quantity %> </td>
			<td> <%= @item.marked_price %> </td>
      <td> <%= time_ago_in_words (@item.created_at) %> ago.</td>
		</tr>
</table>

<%= link_to "Back to #{@user.first_name}'s Item Lists", user_items_path %>

app/views/items/_form_user_items.html.erb
<h1><%= @user.first_name %>'s items list</h1>

<table>
	<tr>
    <th> Item ID </th>
		<th> Item Name </th>
		<th> Stock Quantity </th>
		<th> Marked_Price </th>
		<th> Posted Time </th>
		<% if current_user.id == @user.id %>
			<th> Edit details? </th>
		<% else %>
			<th> Interested? </th>
		<% end %>
	</tr>
  <% @user.items.each do |user| %>
		<tr>
      <td> <%= user.id %> </td>
			<td> <%= user.item_name %> </td>
			<td> <%= user.stock_quantity %> </td>
			<td> <%= user.marked_price %> </td>
      <td> <%= time_ago_in_words (user.created_at) %> ago.</td>
				<% if current_user.id == @user.id %>
				<td> <%= link_to "Edit Items", edit_user_item_path(:current_user_id, user.id)%></td>
				<% else %>
				<td> <%= link_to "Add to Cart", new_order_path %>
				<% end %>
			<% end %>

		</tr>
</table>
<%= link_to "Back to #{@user.first_name}'s profile", user_path %>

app/views/items/current_user_item.html.erb
<%= render 'form_user_item' %>

app/views/items/current_user_items.html.erb
<%= render 'form_user_items' %>

app/views/items/edit.html.erb
<h1>Edit Item!</h1>

<%= form_for ([@user, @item]) do |f| %>
    <div>
      User Name = <%= @user.first_name %>
    </div>

    <div>
        <%= f.label :item_name %>
        <%= f.text_field :item_name %>
    </div>

    <div>
        <%= f.label :stock_quantity %>
        <%= f.number_field :stock_quantity %>
    </div>

    <div>
        <%= f.label :marked_price %>
        <%= f.number_field :marked_price %>
    </div>


    <%= f.submit "Submit!" %>

<% end %>

app/views/items/index.html.erb
<%= render 'form_user_items' %>

app/views/items/new.html.erb
<h1>Upload New Item!</h1>

<%= form_for ([@user, @user.items.build]) do |f| %>
    <div>
      User Name = <%= @user.first_name %>
    </div>

    <div>
        <%= f.label :item_name %>
        <%= f.text_field :item_name %>
    </div>

    <div>
        <%= f.label :stock_quantity %>
        <%= f.number_field :stock_quantity %>
    </div>

    <div>
        <%= f.label :marked_price %>
        <%= f.number_field :marked_price %>
    </div>


    <%= f.submit "Submit!" %>

<% end %>

app/views/items/show.html.erb
<%= render 'form_user_item' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Business4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
	  Logged in as: <%= current_user.first_name %>
	  <%= link_to 'Log Out', logout_path, method: :delete %>
    <%= link_to "Edit My Profile", edit_user_path(current_user)%>
	  <%= link_to "My Items", user_items_path(current_user) %>
    <%= link_to "Upload New Item", new_user_item_path(current_user) %>
	<% else %>
	  <%= link_to 'Log In', login_path %>
	  <%= link_to 'Sign Up', new_user_path %>
	<% end %>
<%= yield %>

</body>
</html>

app/views/orderlines/new.html.erb
<h1>Add new orderline!</h1>

<%= form_for ([@order, @order.orderlines.build]) do |f| %>
    <div>
      Order ID = <%= @order.id %>
    </div>


    <div>
        <%= f.label :quantity %>
        <%= f.number_field :quantity %>
    </div>

    <div>
        <%= f.label :selling_price %>
        <%= f.number_field :selling_price %>
    </div>


    <%= f.submit "Submit!" %>

<% end %>

app/views/orders/index.html.erb
<h1>Orders Lists</h1>


<table>
	<tr>
		<th> Order ID </th>
		<th> Last Name </th>
    <th> Email </th>
		<th> Items Details</th>
		<th> Users Details</th>
	</tr>
    <% @orders.each do |order| %>
		<tr>
			<td> <%= order.id %> </td>

      <% end %>
		</tr>
</table>

app/views/orders/new.html.erb
<h1>Add new order!</h1>

<%= form_for @order do |f| %>
  <div>
  <%= f.text_field :user_id %>
  </div>
  <div>

  </div>
  <div>
    <%= f.submit "Submit!" %>
  </div>
<% end %>

app/views/orders/show.html.erb
<h1><%= @user.first_name %>'s order.</h1>

<table>
	<tr>
    <th> User ID </th>
		<th> Order ID </th>

	</tr>
		<tr>
      <td> <%= @user.id %> </td>
			<td> <%= @order.id %> </td>

		</tr>
</table>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User Profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users Lists</h1>


<table>
	<tr>
		<th> First Name </th>
		<th> Last Name </th>
    <th> Email </th>
		<th> Items Details</th>
		<th> Users Details</th>
	</tr>
    <% @users.each do |user| %>
		<tr>
			<td> <%= user.first_name %> </td>
			<td> <%= user.last_name %> </td>
      <td> <%= user.email %> </td>
      <td> <%= link_to "#{user.first_name}'s Items List", user_items_path(user) %>
			<td> <%= link_to "#{user.first_name}'s Details", particular_user_path(user) %>
      <% end %>
		</tr>
</table>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1> <%= @user.first_name %> </h1>

<table>
	<tr>
		<th> First Name </th>
		<th> Last Name </th>
    <th> Email </th>
		<th> Items Details</th>
	</tr>

		<tr>
			<td> <%= @user.first_name %> </td>
			<td> <%= @user.last_name %> </td>
      <td> <%= @user.email %> </td>
      <td> <%= link_to "#{@user.first_name}'s Items List", user_items_path(@user) %>
		</tr>
</table>
<%= link_to "Back to Users' Lists", users_path %>